"""Models the next two kinds of area's set pieces in Blender: the high tech
city's streets and the militia's bases and outposts.

    python3 tools/procgen/build_kits.py            (both kits)
    python3 tools/procgen/build_kits.py city        (one kit; the other's shapes are kept)
    (or: blender -b --python tools/procgen/build_kits.py -- city)

Writes assets/models/city/<name>.glb and assets/models/military/<name>.glb,
and scripts/run/procgen/kit_shapes.gd: every new model's colliders, grapple
hooks and standing tops, in the same form as prop_shapes.gd, so set_pieces.gd
places them exactly like the generated zones' other pieces.

The pieces themselves live in tools/procgen/city_kit.py and
tools/procgen/military_kit.py. Both use the helpers of
tools/procgen/build_props.py (begin, sbox, tbox, solid, column, hook, top,
footprint, hook_block, part, export...), the same conventions too: low-poly,
flat shaded, objects named "<part>__<material>", origins on the ground, fronts
facing -Y in Blender (+Z in Godot). Orange ("anchor") marks a grapple hook,
blue ("wallrun") a wall made to run or kick off. Glowing signs and strips are
"<part>_<colour>__neon" (cyan, pink, amber, red, green, white): the game lights
them in that colour.

New surface materials for these kits (tools/make_textures.py paints them):
asphalt, pavers, facade (dark composite panels), curtain (glass curtain wall),
corrugated, olive (painted military steel), hesco (mesh-and-fabric barrier
baskets), camo (camouflage cloth), tarmac (pad concrete), neon. The old ones
(concrete, gunmetal, canvas, wood, shadow, light, anchor, wallrun, dirt) still
work.

Seeded, so re-running gives the same meshes.
"""
import re
import sys
from pathlib import Path

import bpy  # noqa: F401  (first: the bpy module brings bmesh and mathutils)

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
_src = (HERE / "build_props.py").read_text().rsplit("\nmain()", 1)[0]
G = {"__file__": str(HERE / "build_props.py"), "__name__": "procgen_build_props"}
exec(compile(_src, "procgen_build_props", "exec"), G)

KITS = {
    "city": HERE / "city_kit.py",
    "military": HERE / "military_kit.py",
}
SHAPES_GD = REPO / "scripts" / "run" / "procgen" / "kit_shapes.gd"


def build(kit):
    """Runs one kit's script in the build_props helpers' namespace and returns
    its pieces' shapes."""
    G["SHAPES"].clear()
    G["OUT"] = REPO / "assets" / "models" / kit
    # The helpers read their globals (OUT, SHAPES, _cur) from G, so the kit
    # must run in G itself.
    exec(compile(KITS[kit].read_text(), KITS[kit].name, "exec"), G)
    G["build_all"]()
    return {name: dict(s) for name, s in G["SHAPES"].items()}


def _v3(v):
    return "Vector3(%.3f, %.3f, %.3f)" % tuple(round(c, 3) + 0.0 for c in v)


def _entries(kit, shapes):
    lines = []
    for name, s in shapes.items():
        lines.append('\t"%s": {' % name)
        lines.append('\t\t"kit": "%s",' % kit)
        lines.append('\t\t"boxes": [%s],' % ", ".join(
            "[%s, %s, %.2f, %.2f]" % (_v3(c), _v3(sz), yaw, tilt) for c, sz, yaw, tilt in s["boxes"]))
        lines.append('\t\t"columns": [%s],' % ", ".join(
            "[%s, %.2f, %.2f]" % (_v3(b), r, h) for b, r, h in s["columns"]))
        lines.append('\t\t"hooks": [%s],' % ", ".join(_v3(h) for h in s["hooks"]))
        lines.append('\t\t"tops": [%s],' % ", ".join(_v3(t) for t in s["tops"]))
        sx, sy = s["size"] or (2.0, 2.0)
        lines.append('\t\t"size": Vector2(%.2f, %.2f),' % (sx, sy))
        lines.append("\t},")
    return lines


def _old_entries():
    """The entries already in kit_shapes.gd, per kit, as text."""
    out = {}
    if not SHAPES_GD.exists():
        return out
    text = SHAPES_GD.read_text()
    for m in re.finditer(r'(\t"[a-z0-9_]+": \{\n\t\t"kit": "([a-z]+)",\n.*?\n\t\},)', text, re.S):
        out.setdefault(m.group(2), []).append(m.group(1))
    return out


def write_shapes(built):
    old = _old_entries()
    lines = [
        "extends RefCounted",
        "## Generated by tools/procgen/build_kits.py: do not edit by hand.",
        "## The city and military kits' models (assets/models/<kit>/<id>.glb):",
        "## colliders (local centre, size, yaw, tilt about X, degrees), columns",
        "## (base, radius, height), grapple hooks and standing tops, and the",
        "## footprint (x, z), all in the model's own frame (front +Z).",
        "",
        "const SHAPES := {",
    ]
    for kit in KITS:
        if kit in built:
            lines += _entries(kit, built[kit])
        else:
            for e in old.get(kit, []):
                lines += e.split("\n")
    lines.append("}")
    SHAPES_GD.write_text("\n".join(lines) + "\n")
    print("wrote", SHAPES_GD)


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else sys.argv[1:]
    want = [a for a in argv if a in KITS] or list(KITS)
    built = {}
    G["clear"]()
    for kit in want:
        built[kit] = build(kit)
    write_shapes(built)


main()
